obj-$(CONFIG_DRIVER_EFUSE) += efuse/
obj-$(CONFIG_DRIVER_IRQCHIP) += irqchip/
obj-y += serial/
obj-$(CONFIG_DRIVER_SD) += sd/
obj-$(CONFIG_DRIVER_SPI_FLASH) += spi-flash/
obj-$(CONFIG_DRIVER_IO) += io/

