#!/bin/sh
#
# set rp veth        Starts rp veth
#

export LD_LIBRARY_PATH=/lib:/lib64:/usr/lib

start() {
	printf "set rp veth: "
	ifconfig veth0 up

    sleep 15
    ip=$(devmem 0x1a1800044)

    ip1=$(( (ip >> 24) & 0xFF ))
    ip2=$(( (ip >> 16) & 0xFF ))
    ip3=$(( (ip >> 8) & 0xFF ))
    ip4=$(( ip & 0xFF ))

    ifconfig veth0 $ip1.$ip2.$ip3.$ip4
    echo "The IP address is: $ip1.$ip2.$ip3.$ip4"
    echo "OK"
}
stop() {
        printf "Stopping rp veth: "
        ifconfig veth0 down
        echo "OK"
}
restart() {
        stop
        start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
