#!/bin/sh
#
# tp_daemon        Starts tp_daemon
#

export LD_LIBRARY_PATH=/lib:/lib64:/usr/lib

# Make sure the tp_daemon progam exists
[ -f /tp_daemon ] || exit 0

umask 077

start() {
        printf "Starting tp_daemon: "
        # if [ ! -d /proc/device-tree/soc/serial* ] && [ -c /dev/ttyV0 ]; then
        #   /tp_daemon 2>&1 > /dev/ttyV0 &
        # else
        #   /tp_daemon &
        # fi
        /tp_daemon > /dev/null 2>&1 &
        echo "OK"
}
stop() {
        printf "Stopping tp_daemon: "
        killall tp_daemon
        echo "OK"
}
restart() {
        stop
        start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
