obj-$(CONFIG_TEST_ARCH_TIMER) +=arch_timer/
obj-$(CONFIG_TEST_FAB) += fab/
obj-$(CONFIG_TEST_GIC) += gic/
obj-$(CONFIG_TEST_HELLO) += hello/
obj-$(CONFIG_TEST_SD) += sd/
obj-$(CONFIG_TEST_FAT32) += fat32/
obj-$(CONFIG_TEST_SMP) += smp/

